name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Docker logout
        run: docker logout
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t mnojpatidar111/awsdeploylearn .
      - name: Publish image to docker hub
        run: docker push mnojpatidar111/awsdeploylearn:latest

  deploy:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:
      - name: Add user to Docker group
        run: sudo usermod -aG docker $USER
        shell: bash
      - name: Restart Docker service
        run: sudo systemctl restart docker
      - name: Print current user
        run: whoami
      - name: Print working directory
        run: pwd
      - name: Pull Image from docker hub
        run: docker pull mnojpatidar111/awsdeploylearn:latest
      - name: Delete old container
        run: docker rm -f awsdeploylearn-container || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name awsdeploylearn-container mnojpatidar111/awsdeploylearn
