name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Update to the latest major version if v4 is available

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Update to the latest version that supports Node.js 20
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Run Unit Tests
        run: mvn test

      - name: Publish Test Results
        if: failure()
        uses: actions/upload-artifact@v4  # Update to the latest version
        with:
          name: test-results
          path: target/surefire-reports

      - name: Check Build Status
        run: echo "Build complete"
